### ISSUE TITLE
unable to install on raspberry pi

### ISSUE THREAD

**Issue by marclundgren** [danielpgross/arp_standin#2]
```
ruby -v
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [arm-linux-gnueabihf]

gem -v
3.2.5

bundler -v
Bundler version 2.4.12
```

```
bundle exec rake install 
Could not find rake-13.0.1, pcaprub-0.13.1, packetfu-1.1.13 in locally installed gems
Run `bundle install` to install missing gems.
```

```
bundle install
Fetching gem metadata from https://rubygems.org/..
Fetching rake 13.0.1

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/2.7.0/cache/rake-13.0.1.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/2.7.0/cache/rake-13.0.1.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/2.7.0/cache/rake-13.0.1.gem`. It is likely that you need to grant write permissions for that path.

Using bundler 2.4.12
Fetching pcaprub 0.13.1

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/2.7.0/cache/pcaprub-0.13.1.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/2.7.0/cache/pcaprub-0.13.1.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/2.7.0/cache/pcaprub-0.13.1.gem`. It is likely that you need to grant write permissions for that path.

Bundler::PermissionError: There was an error while trying to write to
`/var/lib/gems/2.7.0/cache/rake-13.0.1.gem`. It is likely that you need to grant write permissions
for that path.
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/shared_helpers.rb:105:in `rescue in
filesystem_access'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/shared_helpers.rb:102:in `filesystem_access'
/var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:483:in `block in
download_gem'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/retry.rb:40:in `run'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/retry.rb:30:in `attempt'
/var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:474:in
`download_gem'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/source/rubygems.rb:481:in `download_gem'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/source/rubygems.rb:443:in `fetch_gem'
/var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/source/rubygems.rb:427:in
`fetch_gem_if_possible'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/source/rubygems.rb:156:in `install'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/installer/gem_installer.rb:54:in `install'
/var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/installer/parallel_installer.rb:156:in
`do_install'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/installer/parallel_installer.rb:84:in `call'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/installer/parallel_installer.rb:67:in `call'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/installer.rb:244:in `install_in_parallel'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/installer.rb:201:in `install'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/installer.rb:89:in `block in run'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/process_lock.rb:19:in `rescue in lock'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/process_lock.rb:15:in `lock'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/installer.rb:71:in `run'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/installer.rb:23:in `install'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/cli/install.rb:62:in `run'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/cli.rb:261:in `block in install'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/settings.rb:131:in `temporary'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/cli.rb:260:in `install'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in
`invoke_command'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
/var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in
`with_friendly_errors'
  /var/lib/gems/2.7.0/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'

An error occurred while installing rake (13.0.1), and Bundler cannot continue.

In Gemfile:
  rake
```

**Comment by marclundgren** [comment]
I get the same error whe trying to run `./bin/setup`

**Comment by marclundgren** [comment]
update. I ended up installing ruby 3.2.2 and also `apt-get install libpcap-dev`. setup works now
